export class Muziekstuk {
    id?: number; // ? heeft te maken met autogenerated id
    titel: string;
    artiest: string;
    omschrijving: string;
    lesonderdeel: string;
    padMp3: string;
    padXml: string;
    padPictogram: string;
    //mp3:              string;
    xml: string;
    //pictogram:        string;
}