// Class bestand, dus geen component!
// Naamgeving MOET overeenkomen met naamgeving backend (getters/setters -> postman)
export class Muziekstuk {
  id?:              number; // ? heeft te maken met autogenerated id
  titel:            string;
  artiest:          string;
  omschrijving:     string;
  xml:              string;
  pictogram:        string;
  // padMp3:           string;
  // mp3:              string;
}